apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  serviceName: database
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: database
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: database
        image: {{ .Values.database.image }}:{{ .Values.tag }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: user-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: root-password
        - name: MYSQL_USER
          value: {{ .Values.database.username }}
        - name: MYSQL_DATABASE
          value: {{ .Values.database.database }}
        ports:
        - name: database
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
            claimName: database-storage
