apiVersion: v1
kind: Secret
metadata:
  name: database
  labels:
    app.kubernetes.io/component: database
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.root_password }}
  root-password: {{ .Values.database.root_password | b64enc | quote }}
  {{- else }}
  root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.password }}
  user-password:  {{ .Values.database.password | b64enc | quote }}
  {{- else }}
  user-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
