apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-storage
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
