apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
  - name: database
    port: 3306
    targetPort: 3306
  selector:
    app.kubernetes.io/name: database
    app.kubernetes.io/instance: {{ .Release.Name }}
