apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-storage
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
