apiVersion: v1
kind: Service
metadata:
  name: server
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: {{ .Release.Name }}
